---
title: California's 27th - Post-election Campaign Narrative
author: Giovanni Salcedo
date: '2022-12-05'
slug: []
categories: []
tags: []
summary: In my final post, I break down what happened in the election that was the tipping point for Republicans gaining control of the House in the 2022 midterms.
---

*This blog is part of a series for Gov 1347: Election Analytics, a course at [Harvard University](https://www.harvard.edu/) taught by Professor [Ryan D. Enos](http://ryandenos.com/)*.

# Introduction

Since my last post about two weeks ago, more votes have been counted, and all House races have been called by the Associated Press except for Colorado's 3rd district, [which is heading to a recount](https://www.cpr.org/2022/12/01/state-orders-recount-boebert-frisch-race-district-3/) because incumbent Republican Rep. Lauren Boebert leads by only 550 votes, though the recount is widely expected to not change the outcome. Thus, Republicans are set to win 222 House seats in total while Democrats will have 213, a very thin five-seat majority for Republicans.

But the race that [first gave Republicans the 218 seats](https://apnews.com/article/house-control-republicans-2022-election-explained-947add904c9372b99869773332898076) needed to officially lock in the majority was decided in a district just north of Los Angeles, California. The incumbent Rep. Mike Garcia, a Republican, managed to fend off Democratic challenger Christy Smith for the third time in a row since 2020, winning 53.2% of the vote to Smith's 46.8% [as of November 29](https://www.nytimes.com/interactive/2022/11/08/us/elections/results-california-us-house-district-27.html). As I'll show later on, Garcia did better than the fundamentals of his district, the polls, and forecasts suggested he should have done.

In a year where Democrats for the most part defied political gravity and significantly minimized their losses in a very unfavorable midterm year, how did Garcia do *better* than his November 2020 race, when he was reelected by just 333 votes? Even though by election day most forecasts and expert predictions gave just the slightest advantage to Garcia, why did he still manage to win by over 6 points in a Democratic-leaning district?

# A Brief Overview of CA-27

Before redistricting changed many district boundaries and made my work and analysis much more annoying, the old CA-25 covered most of the land that is now covered by CA-27. Today, CA-27 covers all of Santa Clarita, Lancaster, and Palmdale in southern California. The most major change from the old CA-25 map is that the district no longer covers the Republican-heavy Simi Valley, shifting the political lean of the district towards the Democrats enough that [Garcia himself complained about the decision](https://www.nytimes.com/interactive/2022/11/08/us/elections/results-california-us-house-district-27.html), which was made by a nonpartisan commission.

Unfortunately, there is no updated demographic info for the new CA-27 specifically, but there is data from the 2020 census for the old CA-25 map which has very similar boundaries either way. [According to Ballotpedia](https://ballotpedia.org/California%27s_25th_Congressional_District), the old CA-25 had a population of 753,744. The racial breakdown was 43.7% White, 8.8% Asian, 8.4% Black, 1.4% Native American, and 0.2% Pacific Islander, and 42.1% of the population was ethnically Hispanic. The median household income in the old CA-25 was \$83,267, higher than the [2020 national median](https://www.census.gov/library/publications/2022/demo/p60-276.html) of \$71,186, and the college graduation rate was 28.7%.

What's most significant about this district in terms of its demographics comes from its party registration numbers. [Of the registered voters in the new CA-27 map](https://calmatters.org/california-voter-guide-2022/us-house/house-races/#hot-district-27), 41.7% are Democrats, 29.2% are Republicans, and 21.6% are registered as having no party preference. The Cook PVI, which measures how strongly a district leans towards one party, for this district is [D+4](https://www.cookpolitical.com/cook-pvi/2022-partisan-voting-index/district-map-and-list), meaning it performed about four points more Democratic in the two-party vote share in the previous two presidential elections than the nation as a whole. While certainly nowhere near a slam-dunk Democratic district, the demographics here somewhat favor Democrats over Republicans, making Garcia's continued success in this district quite interesting.

In 2016 and before, the district (CA-25) was a GOP stronghold, but in 2018, Democrat Katie Hill flipped the seat blue with 54.4% of the vote, riding the blue wave of the midterm elections that year. Nevertheless, Hill's resignation following a scandal opened up the seat, with a special election taking place early in 2020. In that election, Mike Garcia beat Christy Smith with 54.9% of the vote to her 45.1%, a flipped image result of 2018. As I discussed above, Garcia faced a much tougher challenge in the November presidential election to hold his seat, but he held on by the slimmest of margins. Now, he will represent CA-27 for two years, likely running for reelection in the 2024 election.
