---
title: Final 2022 Election Prediction
author: Giovanni Salcedo
date: '2022-11-06'
slug: []
categories: []
tags: []
summary: In this post, I reveal and break down my final national House of Representatives prediction for the 2022 midterms. What percentage of the popular vote and how many seats will Democrats win? Click to find out!
---



<p><em>This blog is part of a series for Gov 1347: Election Analytics, a course at <a href="https://www.harvard.edu/">Harvard University</a> taught by Professor <a href="http://ryandenos.com/">Ryan D. Enos</a></em>.</p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p><strong>It’s finally here.</strong></p>
<p>Election Day has finally arrived, and I know my lovely blog audience has been eagerly awaiting my final prediction for the “most important election in our lifetime” (or as <a href="https://slate.com/news-and-politics/2020/11/most-important-election-of-our-lifetimes-history.html">every</a> <a href="https://slate.com/news-and-politics/2020/11/most-important-election-of-our-lifetimes-history.html">election</a> ever seems to be). This post will provide a full breakdown of my final national model - which predicts both Democrats’ national two-party vote share and the number of Democratic House seats - and an interpretation of the results.</p>
</div>
<div id="formula-and-variables" class="section level1">
<h1>Formula and Variables</h1>
<p>Since two weeks ago, I made several changes to the variables I incorporate into my model. Notably, I have decided to leave out data from the 2020 election entirely due to the highly unusual circumstances of the election taking place during the COVID-19 pandemic.</p>
<p><img src="images/Screenshot%202022-11-07%20at%209.25.59%20AM.png" /></p>
<p><img src="images/Screenshot%202022-11-07%20at%209.29.44%20AM.png" /></p>
<p>Above are the formulas for the vote share and seat share versions of the model. As you can see, both use the same independent variables, differing only in the dependent variable. Below I break down each of the four independent variables I’ve chosen to use for my model:</p>
<p><strong>1. Unemployment rate:</strong> Specifically, I use the percent change in the unemployment rate between the third and fourth quarter of the election year. I use the last few months of unemployment data since it is what people will be experiencing at the time of the election, and I now am using percent change to better capture major changes to unemployment close to an election that would be more noticeable to voters.</p>
<p><strong>2. Real disposable income:</strong> I decided to include another economic variable, seeing as how often the economy is played up as one of the most important issues in this election and almost every other election. Similarly to the unemployment rate variable, I use the percent change in RDI between the third and fourth quarter of the election year.</p>
<p><strong>3. Average democratic generic ballot support:</strong> Based on past elections, the generic ballot continues to be a powerful tool for helping us predict the final results of the election. I incorporate the last 100 days of generic ballot polls before the election since the closer the election is, the closer the polls seem to converge on the final result.</p>
<p><strong>4. Incumbent party of the president:</strong> I decided to just focus on this incumbency variable, based on the conventional wisdom that midterm elections are bad for the incumbent president’s party specifically, even if the opposing party is in control of the House or Senate. It measures whether the incumbent president at the time of the election is a Democrat (1) or a Republican (0).</p>
</div>
<div id="regression-tables" class="section level1">
<h1>Regression Tables</h1>
<div id="vote-share" class="section level3">
<h3>Vote Share</h3>
<div id="bpgfeyzprf" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#bpgfeyzprf .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bpgfeyzprf .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bpgfeyzprf .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bpgfeyzprf .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bpgfeyzprf .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bpgfeyzprf .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bpgfeyzprf .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bpgfeyzprf .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bpgfeyzprf .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bpgfeyzprf .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bpgfeyzprf .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bpgfeyzprf .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#bpgfeyzprf .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bpgfeyzprf .gt_from_md > :first-child {
  margin-top: 0;
}

#bpgfeyzprf .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bpgfeyzprf .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bpgfeyzprf .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bpgfeyzprf .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bpgfeyzprf .gt_row_group_first td {
  border-top-width: 2px;
}

#bpgfeyzprf .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpgfeyzprf .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bpgfeyzprf .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bpgfeyzprf .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bpgfeyzprf .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpgfeyzprf .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bpgfeyzprf .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bpgfeyzprf .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bpgfeyzprf .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bpgfeyzprf .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpgfeyzprf .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bpgfeyzprf .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bpgfeyzprf .gt_left {
  text-align: left;
}

#bpgfeyzprf .gt_center {
  text-align: center;
}

#bpgfeyzprf .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bpgfeyzprf .gt_font_normal {
  font-weight: normal;
}

#bpgfeyzprf .gt_font_bold {
  font-weight: bold;
}

#bpgfeyzprf .gt_font_italic {
  font-style: italic;
}

#bpgfeyzprf .gt_super {
  font-size: 65%;
}

#bpgfeyzprf .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#bpgfeyzprf .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bpgfeyzprf .gt_indent_1 {
  text-indent: 5px;
}

#bpgfeyzprf .gt_indent_2 {
  text-indent: 10px;
}

#bpgfeyzprf .gt_indent_3 {
  text-indent: 15px;
}

#bpgfeyzprf .gt_indent_4 {
  text-indent: 20px;
}

#bpgfeyzprf .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-weight: bold;">(Intercept)</td>
<td class="gt_row gt_center">31</td>
<td class="gt_row gt_center">23, 39</td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">ue_pct_chg</td>
<td class="gt_row gt_center">0.03</td>
<td class="gt_row gt_center">-0.13, 0.20</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">rdi_pct_chg</td>
<td class="gt_row gt_center">-0.11</td>
<td class="gt_row gt_center">-0.99, 0.76</td>
<td class="gt_row gt_center">0.8</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">avg_D_support</td>
<td class="gt_row gt_center">0.47</td>
<td class="gt_row gt_center">0.30, 0.63</td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">pres_incumb</td>
<td class="gt_row gt_center">-2.7</td>
<td class="gt_row gt_center">-4.3, -1.1</td>
<td class="gt_row gt_center" style="font-weight: bold;">0.002</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="4">Adjusted R² = 0.689</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><sup class="gt_footnote_marks">1</sup> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
<p>Above is a table showing the output of the regression of vote share on the independent variables. Interestingly, the two economic variables - percent change in unemployment rate and RDI - were not statistically significant. However, the other two variables in my model were both statistically significant, with p-values well under 0.05. The coefficient for “avg_D_support” is 0.47, which means that for every 1 percent increase in average generic ballot poll support for Democrats, Democrats gain about 0.47% in the popular vote. This relationship shows that if Democrats have the poll numbers, they will likely translate some of that into votes on Election Day. On the other hand, the coefficient for “pres_incumb” is -2.7, which means that if the incumbent president is a Democrat, Democrats are penalized about 2.7% in the popular vote. This result falls in line with the conventional wisdom of parties performing more poorly when their party has the presidency. The adjusted R-squared for this regression is 0.689, which is a nice increase from two weeks ago, when the adjusted R-squared for the vote share regression was 0.468. Thus, this model has arguably good in-sample fit, especially when compared to my other models during the course of this semester.</p>
</div>
<div id="seat-share" class="section level3">
<h3>Seat Share</h3>
<div id="qkwjtlstrj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#qkwjtlstrj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#qkwjtlstrj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qkwjtlstrj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qkwjtlstrj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qkwjtlstrj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qkwjtlstrj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qkwjtlstrj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qkwjtlstrj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qkwjtlstrj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qkwjtlstrj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qkwjtlstrj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qkwjtlstrj .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#qkwjtlstrj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qkwjtlstrj .gt_from_md > :first-child {
  margin-top: 0;
}

#qkwjtlstrj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qkwjtlstrj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qkwjtlstrj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#qkwjtlstrj .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#qkwjtlstrj .gt_row_group_first td {
  border-top-width: 2px;
}

#qkwjtlstrj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qkwjtlstrj .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#qkwjtlstrj .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#qkwjtlstrj .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qkwjtlstrj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qkwjtlstrj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qkwjtlstrj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qkwjtlstrj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qkwjtlstrj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qkwjtlstrj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qkwjtlstrj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qkwjtlstrj .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qkwjtlstrj .gt_left {
  text-align: left;
}

#qkwjtlstrj .gt_center {
  text-align: center;
}

#qkwjtlstrj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qkwjtlstrj .gt_font_normal {
  font-weight: normal;
}

#qkwjtlstrj .gt_font_bold {
  font-weight: bold;
}

#qkwjtlstrj .gt_font_italic {
  font-style: italic;
}

#qkwjtlstrj .gt_super {
  font-size: 65%;
}

#qkwjtlstrj .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#qkwjtlstrj .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#qkwjtlstrj .gt_indent_1 {
  text-indent: 5px;
}

#qkwjtlstrj .gt_indent_2 {
  text-indent: 10px;
}

#qkwjtlstrj .gt_indent_3 {
  text-indent: 15px;
}

#qkwjtlstrj .gt_indent_4 {
  text-indent: 20px;
}

#qkwjtlstrj .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>95% CI</strong><sup class="gt_footnote_marks">1</sup></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-weight: bold;">(Intercept)</td>
<td class="gt_row gt_center">13</td>
<td class="gt_row gt_center">-68, 94</td>
<td class="gt_row gt_center">0.7</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">ue_pct_chg</td>
<td class="gt_row gt_center">-0.38</td>
<td class="gt_row gt_center">-2.0, 1.3</td>
<td class="gt_row gt_center">0.6</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">rdi_pct_chg</td>
<td class="gt_row gt_center">-4.6</td>
<td class="gt_row gt_center">-13, 4.3</td>
<td class="gt_row gt_center">0.3</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">avg_D_support</td>
<td class="gt_row gt_center">5.0</td>
<td class="gt_row gt_center">3.3, 6.7</td>
<td class="gt_row gt_center" style="font-weight: bold;"><0.001</td></tr>
    <tr><td class="gt_row gt_left" style="font-weight: bold;">pres_incumb</td>
<td class="gt_row gt_center">-21</td>
<td class="gt_row gt_center">-37, -4.7</td>
<td class="gt_row gt_center" style="font-weight: bold;">0.014</td></tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="4">Adjusted R² = 0.656</td>
    </tr>
  </tfoot>
  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><sup class="gt_footnote_marks">1</sup> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>
<p>Above is a table showing the output of the regression of seat share on the independent variables. As was the case in the vote share regression, the economic variables are again not statistically significant. I would think that the change in unemployment and RDI would factor into voters’ decision making when choosing which party to vote for, especially if these changes are large, but this result could just be due to how I created these variables. The non-economic variables were again statistically significant with p-values well below 0.05. The coefficient for “avg_D_support” is 5.0, which means that every 1% increase in average generic ballot support translates to about a gain of 5 House seats for the Democrats. The coefficient for “pres_incumb” is -21, which means that if a Democrat currently holds the White House, Democrats are expected to lose an additional 21 House seats. These results are not too different from the vote share regression and fall in line with my expectations and the conventional wisdom. The adjusted R-squared in this case is 0.656, not too different than the vote share regression and definitely higher than the adjusted-R squared from the model from two weeks ago (0.549). Just like my vote share model, this model also arguably has good in-sample fit.</p>
</div>
</div>
<div id="out-of-sample-testing" class="section level1">
<h1>Out-Of-Sample Testing</h1>
<p>For both the vote share and seat share regressions, I will pull out the data from 2018 and use it to test the model’s ability to predict values outside of the sample.</p>
<pre><code>##         1 
## -1.079743</code></pre>
<p>When taking the data for the year 2018 out of the original model and predicting it as if it were outside the sample, the predicted Democratic vote share is about 1.08% less than the true result for 2018. Although 1.08 isn’t a huge difference, in terms of the popular vote for the House, it can mean the difference between winning or losing the majority, so this test shows that there is still quite a bit of uncertainty using this model to predict elections outside of the sample.</p>
<pre><code>##        1 
## 14.25989</code></pre>
<p>The model’s uncertainty is even more visible when looking at seat share. Here, the model’s prediction is about 14 seats higher than the actual result for 2018. Again, 14 seats is not huge, but it can definitely sway the majority one way or the other.</p>
</div>
<div id="final-prediction" class="section level1">
<h1>Final Prediction</h1>
<p>Below represents what you’ve all been waiting for: how will the Democrats fare on Tuesday??</p>
<pre><code>##        fit      lwr      upr
## 1 49.70226 45.48201 53.92251</code></pre>
<p>My model predicts that <strong>Democrats will win about 49.7% of the popular vote.</strong> This margin would represent an extremely close race, though with a slight edge for the Republicans. The model suggests we could see a vote share for Democrats anywhere between 45.48% and 53.92%, a range that’s somewhat wide, reflecting the uncertainty of the model and of this election in general.</p>
<pre><code>##        fit      lwr     upr
## 1 214.7462 171.9684 257.524</code></pre>
<p>As for seats, my model predicts that <strong>Democrats will win about 215 seats.</strong> This result means that Democrats are projected to lose their majority in the House by just three seats, the slimmest of margins. The model suggests we could see a seat share for Democrats anywhere between 172 seats and 258 seats, a very wide range. This suggests to me that the seat share model is even more uncertain of what to predict for the final number of seats that Democrats will win, since it includes both a Republican landslide and Democratic landslide scenario.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-1-1.png" width="672" /><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<p>Finally, above are visualizations of my prediction intervals. As you can see, Democrats are just shy of a majority of the popular vote and seats, but the upper and lower bounds are so large that technically anything is possible.</p>
</div>
